/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mccow.View;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author enrique
 */
public class MainView extends javax.swing.JFrame {
    //List<MesaView> mesasView1 = new ArrayList<>();
    //List<MesaView> mesasView2 = new ArrayList<>();
    MesaView mesasView3 = new MesaView();
    /**
     * Creates new form prueba
     */
    public MainView() {
        initComponents();
        
        /*for(int i = 0;i<6;i++){
            mesasView1.add(new MesaView());
        }
        for(MesaView m: mesasView1){
            pnlMesas1.add(m);
        }
        
        for(int i = 0;i<4;i++){
            mesasView2.add(new MesaView());
        }
        for(MesaView m2: mesasView2){
            pnlMesas2.add(m2);
        }*/
        
        pnlMesas3.add(mesasView3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMesas1 = new javax.swing.JPanel();
        pnlMesas2 = new javax.swing.JPanel();
        pnlMesas3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMesas1.setLayout(new java.awt.GridLayout(2, 3));
        getContentPane().add(pnlMesas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 370, 310));

        pnlMesas2.setLayout(new java.awt.GridLayout(2, 2));
        getContentPane().add(pnlMesas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 310, 310));

        pnlMesas3.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(pnlMesas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 120, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mccow/Imagenes/SueloBricks.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 1030, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlMesas1;
    private javax.swing.JPanel pnlMesas2;
    private javax.swing.JPanel pnlMesas3;
    // End of variables declaration//GEN-END:variables
}
